-- MySQL Script generated by MySQL Workbench
-- Sun Feb 25 18:54:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WALLETHUB_DB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WALLETHUB_DB` ;

-- -----------------------------------------------------
-- Schema WALLETHUB_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WALLETHUB_DB` DEFAULT CHARACTER SET utf8 ;
USE `WALLETHUB_DB` ;

-- -----------------------------------------------------
-- Table `WALLETHUB_DB`.`FrequentIp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WALLETHUB_DB`.`FrequentIp` ;

CREATE TABLE IF NOT EXISTS `WALLETHUB_DB`.`FrequentIp` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(45) NOT NULL,
  `frequency` INT NULL,
  `comments` VARCHAR(100) NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WALLETHUB_DB`.`Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WALLETHUB_DB`.`Log` ;

CREATE TABLE IF NOT EXISTS `WALLETHUB_DB`.`Log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(45) NOT NULL,
  `date` DATETIME NULL,
  `request` VARCHAR(255) NULL,
  `status` INT NULL,
  `userAgent` VARCHAR(255) NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
